# Proyecto módulo : ETL

## Extract: Imports y carga de archivos

In [1]:
# Tratamiento y manipulación de datos
import pandas as pd
import numpy as np

# Visualización de datos
import matplotlib.pyplot as plt
import seaborn as sns

# Gestión de alertas y configuración visual
import warnings
warnings.filterwarnings("ignore")

# Configuración de Pandas para visualizar todas las columnas
pd.set_option('display.max_columns', None)

# Cargar los datasets
df_remote_work = pd.read_csv('./datasets/Impact_of_Remote_Work_on_Mental_Health.csv')
df_survey = pd.read_csv('./datasets/survey.csv')

## Transform: EDA y limpieza

### Remote Work

In [2]:
df_remote_work.head()

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
0,EMP0001,32,Non-binary,HR,Healthcare,13,Hybrid,47,7,2,Medium,Depression,No,Decrease,1,Unsatisfied,1,Weekly,Good,Europe
1,EMP0002,40,Female,Data Scientist,IT,3,Remote,52,4,1,Medium,Anxiety,No,Increase,3,Satisfied,2,Weekly,Good,Asia
2,EMP0003,59,Non-binary,Software Engineer,Education,22,Hybrid,46,11,5,Medium,Anxiety,No,No Change,4,Unsatisfied,5,NaN,Poor,North America
3,EMP0004,27,Male,Software Engineer,Finance,20,Onsite,32,8,4,High,Depression,Yes,Increase,3,Unsatisfied,3,NaN,Poor,Europe
4,EMP0005,49,Male,Sales,Consulting,32,Onsite,35,12,2,High,NaN,Yes,Decrease,3,Unsatisfied,3,Weekly,Average,North America

In [4]:
df_remote_work.tail()

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
4995,EMP4996,32,Male,Sales,Consulting,4,Onsite,24,2,5,High,Burnout,Yes,Decrease,4,Neutral,1,Weekly,Average,Asia
4996,EMP4997,39,Female,Sales,Healthcare,27,Onsite,48,15,1,Low,Depression,Yes,Decrease,1,Satisfied,1,NaN,Average,Africa
4997,EMP4998,42,Female,Sales,Healthcare,21,Hybrid,34,1,4,High,Burnout,No,Increase,3,Satisfied,1,Daily,Poor,Oceania
4998,EMP4999,27,Female,Sales,Healthcare,26,Remote,58,0,5,Low,NaN,Yes,Increase,3,Unsatisfied,4,Daily,Average,Asia
4999,EMP5000,29,Male,HR,IT,30,Onsite,20,15,1,Low,Depression,Yes,No Change,3,Unsatisfied,5,NaN,Poor,Asia

In [6]:
df_remote_work.sample(5)

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
3286,EMP3287,31,Prefer not to say,Data Scientist,IT,4,Hybrid,50,0,1,Low,Burnout,Yes,Decrease,2,Unsatisfied,1,Daily,Good,Asia
1308,EMP1309,28,Non-binary,Project Manager,Healthcare,2,Onsite,48,0,2,High,Depression,Yes,No Change,4,Unsatisfied,1,NaN,Good,Oceania
927,EMP0928,59,Prefer not to say,Sales,IT,27,Onsite,27,7,4,Medium,Depression,No,Decrease,3,Neutral,4,Weekly,Good,Asia
72,EMP0073,28,Prefer not to say,Designer,Retail,15,Onsite,30,14,5,High,Burnout,Yes,No Change,2,Unsatisfied,1,Weekly,Good,Africa
2802,EMP2803,53,Non-binary,HR,Healthcare,19,Onsite,38,9,5,Medium,Depression,No,Decrease,1,Unsatisfied,3,Weekly,Good,South America

In [8]:
df_remote_work.shape

(5000, 20)

In [11]:
df_remote_work.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Employee_ID                        5000 non-null   object
 1   Age                                5000 non-null   int64
 2   Gender                             5000 non-null   object
 3   Job_Role                           5000 non-null   object
 4   Industry                           5000 non-null   object
 5   Years_of_Experience                5000 non-null   int64
 6   Work_Location                      5000 non-null   object
 7   Hours_Worked_Per_Week              5000 non-null   int64
 8   Number_of_Virtual_Meetings         5000 non-null   int64
 9   Work_Life_Balance_Rating           5000 non-null   int64
 10  Stress_Level                       5000 non-null   object
 11  Mental_Health_Condition            3804 non-null   object
 12  Access_to_Mental_Health_Resources  5000 non-null   object
 13  Productivity_Change                5000 non-null   object
 14  Social_Isolation_Rating            5000 non-null   int64
 15  Satisfaction_with_Remote_Work      5000 non-null   object
 16  Company_Support_for_Remote_Work    5000 non-null   int64
 17  Physical_Activity                  3371 non-null   object
 18  Sleep_Quality                      5000 non-null   object
 19  Region                             5000 non-null   object
dtypes: int64(7), object(13)
memory usage: 781.4+ KB

In [12]:
df_remote_work.duplicated().sum()

0

In [13]:
df_remote_work.duplicated(subset='Employee_ID').sum()

0

In [ ]:
df_remote_work.columns

Index(['Employee_ID', 'Age', 'Gender', 'Job_Role', 'Industry',
       'Years_of_Experience', 'Work_Location', 'Hours_Worked_Per_Week',
       'Number_of_Virtual_Meetings', 'Work_Life_Balance_Rating',
       'Stress_Level', 'Mental_Health_Condition',
       'Access_to_Mental_Health_Resources', 'Productivity_Change',
       'Social_Isolation_Rating', 'Satisfaction_with_Remote_Work',
       'Company_Support_for_Remote_Work', 'Physical_Activity', 'Sleep_Quality',
       'Region'],
      dtype='object')

In [20]:
df_remote_work.columns = (
    df_remote_work.columns
      .str.strip()                 # quita espacios al inicio/fin
      .str.lower()
      .str.replace(r"\s+", "_", regex=True))  # cualquier espacio → "_"

In [51]:
df_remote_work.describe().T

,count,mean,std,min,25%,50%,75%,max
age,5000.0,40.9950,11.296021,22.0,31.0,41.0,51.0,60.0
years_of_experience,5000.0,17.8102,10.020412,1.0,9.0,18.0,26.0,35.0
hours_worked_per_week,5000.0,39.6146,11.860194,20.0,29.0,40.0,50.0,60.0
number_of_virtual_meetings,5000.0,7.5590,4.636121,0.0,4.0,8.0,12.0,15.0
work_life_balance_rating,5000.0,2.9842,1.410513,1.0,2.0,3.0,4.0,5.0
social_isolation_rating,5000.0,2.9938,1.394615,1.0,2.0,3.0,4.0,5.0
company_support_for_remote_work,5000.0,3.0078,1.399046,1.0,2.0,3.0,4.0,5.0

In [52]:
df_remote_work.describe(include='object').T

                                  count unique              top  freq
employee_id                        5000   5000          EMP0001     1
gender                             5000      4           Female  1274
job_role                           5000      7  Project Manager   738
industry                           5000      7          Finance   747
work_location                      5000      3           Remote  1714
stress_level                       5000      3             High  1686
mental_health_condition            3804      3          Burnout  1280
access_to_mental_health_resources  5000      2               No  2553
productivity_change                5000      3         Decrease  1737
satisfaction_with_remote_work      5000      3      Unsatisfied  1677
physical_activity                  3371      2           Weekly  1755
sleep_quality                      5000      3             Good  1687
region                             5000      6          Oceania   867

#### Columnas

In [21]:
df_remote_work.columns

Index(['employee_id', 'age', 'gender', 'job_role', 'industry',
       'years_of_experience', 'work_location', 'hours_worked_per_week',
       'number_of_virtual_meetings', 'work_life_balance_rating',
       'stress_level', 'mental_health_condition',
       'access_to_mental_health_resources', 'productivity_change',
       'social_isolation_rating', 'satisfaction_with_remote_work',
       'company_support_for_remote_work', 'physical_activity', 'sleep_quality',
       'region'],
      dtype='object')

In [22]:
df_remote_work['employee_id'].nunique()

5000

In [25]:
df_remote_work['age'].nunique()

39

In [24]:
print(sorted(df_remote_work['age'].unique()))

[22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]

In [67]:
df_remote_work['gender'].unique()

array(['Non-binary', 'Female', 'Male', 'Prefer not to say'], dtype=object)

In [66]:
df_remote_work['job_role'].unique()

array(['HR', 'Data Scientist', 'Software Engineer', 'Sales', 'Marketing',
       'Designer', 'Project Manager'], dtype=object)

In [65]:
df_remote_work['industry'].unique()

array(['Healthcare', 'IT', 'Education', 'Finance', 'Consulting',
       'Manufacturing', 'Retail'], dtype=object)

In [32]:
df_remote_work['years_of_experience'].nunique()

35

In [31]:
print(sorted(df_remote_work['years_of_experience'].unique()))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

In [64]:
df_remote_work['work_location'].unique()

array(['Hybrid', 'Remote', 'Onsite'], dtype=object)

In [35]:
df_remote_work['hours_worked_per_week'].nunique()

41

In [36]:
print(sorted(df_remote_work['hours_worked_per_week'].unique()))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]

In [37]:
df_remote_work['number_of_virtual_meetings'].nunique()

16

In [39]:
print(sorted(df_remote_work['number_of_virtual_meetings'].unique()))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [63]:
df_remote_work['work_life_balance_rating'].unique()

array([2, 1, 5, 4, 3], dtype=int64)

In [62]:
df_remote_work['stress_level'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [61]:
df_remote_work['mental_health_condition'].unique()

array(['Depression', 'Anxiety', nan, 'Burnout'], dtype=object)

In [110]:
df_remote_work['mental_health_condition'] = df_remote_work['mental_health_condition'].fillna('Unknown')

In [43]:
df_remote_work['access_to_mental_health_resources'].unique()

array(['No', 'Yes'], dtype=object)

In [44]:
df_remote_work['productivity_change'].unique()

array(['Decrease', 'Increase', 'No Change'], dtype=object)

In [45]:
df_remote_work['social_isolation_rating'].unique()

array([1, 3, 4, 5, 2], dtype=int64)

In [46]:
df_remote_work['satisfaction_with_remote_work'].unique()

array(['Unsatisfied', 'Satisfied', 'Neutral'], dtype=object)

In [47]:
df_remote_work['company_support_for_remote_work'].unique()

array([1, 2, 5, 3, 4], dtype=int64)

In [48]:
df_remote_work['physical_activity'].unique()

array(['Weekly', nan, 'Daily'], dtype=object)

In [111]:
df_remote_work['physical_activity'] = df_remote_work['physical_activity'].fillna('Unknown')

In [49]:
df_remote_work['sleep_quality'].unique()

array(['Good', 'Poor', 'Average'], dtype=object)

In [50]:
df_remote_work['region'].unique()

array(['Europe', 'Asia', 'North America', 'South America', 'Oceania',
       'Africa'], dtype=object)

In [112]:
df_remote_work.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   employee_id                        5000 non-null   object
 1   age                                5000 non-null   int64
 2   gender                             5000 non-null   object
 3   job_role                           5000 non-null   object
 4   industry                           5000 non-null   object
 5   years_of_experience                5000 non-null   int64
 6   work_location                      5000 non-null   object
 7   hours_worked_per_week              5000 non-null   int64
 8   number_of_virtual_meetings         5000 non-null   int64
 9   work_life_balance_rating           5000 non-null   int64
 10  stress_level                       5000 non-null   object
 11  mental_health_condition            5000 non-null   object
 12  access_to_mental_health_resources  5000 non-null   object
 13  productivity_change                5000 non-null   object
 14  social_isolation_rating            5000 non-null   int64
 15  satisfaction_with_remote_work      5000 non-null   object
 16  company_support_for_remote_work    5000 non-null   int64
 17  physical_activity                  5000 non-null   object
 18  sleep_quality                      5000 non-null   object
 19  region                             5000 non-null   object
dtypes: int64(7), object(13)
memory usage: 781.4+ KB

## Survey

In [68]:
df_survey.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,No,Yes,Yes,Not sure,No,Yes,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,No,No,Don't know,No,Don't know,Don't know,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,No,Yes,No,No,No,No,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,No,Yes,No,Yes,No,No,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,Yes,Yes,Yes,No,Don't know,Don't know,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [69]:
df_survey.tail()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,No,Yes,No,No,No,No,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,Yes,Yes,Yes,Yes,No,No,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,No,Yes,Yes,Yes,No,No,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,Yes,Yes,No,Yes,No,No,Don't know,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,No,No,Yes,Yes,No,No,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [70]:
df_survey.sample(5)

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
966,2014-08-29 05:57:48,26,Female,United Kingdom,NaN,Yes,Yes,Yes,Sometimes,1-5,Yes,Yes,No,No,No,No,Don't know,Very easy,Maybe,No,Some of them,Yes,No,Maybe,Yes,No,I am a Trans woman and suffer from depression ...
883,2014-08-28 17:23:19,36,male,United States,VA,Yes,No,No,Never,1-5,No,Yes,Yes,No,No,Don't know,Don't know,Somewhat difficult,No,No,Some of them,Yes,Yes,Yes,Yes,No,NaN
331,2014-08-27 14:33:44,25,Male,Canada,NaN,No,Yes,Yes,Sometimes,More than 1000,No,Yes,Yes,Yes,No,Don't know,Don't know,Don't know,Yes,Maybe,Some of them,No,No,No,No,No,NaN
372,2014-08-27 15:21:59,55,M,United States,PA,No,Yes,Yes,Rarely,More than 1000,No,Yes,Yes,Yes,Yes,Yes,Yes,Very easy,No,No,Yes,Yes,No,No,Yes,No,My refer to the mental health issue of depress...
1215,2015-02-21 09:29:20,28,male,Netherlands,NaN,No,No,No,NaN,6-25,No,Yes,No,Not sure,No,No,Don't know,Somewhat easy,Maybe,Maybe,Some of them,Some of them,No,No,Don't know,No,NaN

In [72]:
df_survey.shape

(1259, 27)

In [ ]:
df_survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1259 non-null   object
 1   Age                        1259 non-null   int64
 2   Gender                     1259 non-null   object
 3   Country                    1259 non-null   object
 4   state                      744 non-null    object
 5   self_employed              1241 non-null   object
 6   family_history             1259 non-null   object
 7   treatment                  1259 non-null   object
 8   work_interfere             995 non-null    object
 9   no_employees               1259 non-null   object
 10  remote_work                1259 non-null   object
 11  tech_company               1259 non-null   object
 12  benefits                   1259 non-null   object
 13  care_options               1259 non-null   object
 14  wellness_program           1259 non-null   object
 15  seek_help                  1259 non-null   object
 16  anonymity                  1259 non-null   object
 17  leave                      1259 non-null   object
 18  mental_health_consequence  1259 non-null   object
 19  phys_health_consequence    1259 non-null   object
 20  coworkers                  1259 non-null   object
 21  supervisor                 1259 non-null   object
 22  mental_health_interview    1259 non-null   object
 23  phys_health_interview      1259 non-null   object
 24  mental_vs_physical         1259 non-null   object
 25  obs_consequence            1259 non-null   object
 26  comments                   164 non-null    object
dtypes: int64(1), object(26)
memory usage: 265.7+ KB

In [74]:
df_survey.duplicated().sum()

0

In [75]:
df_survey.duplicated(subset='Timestamp').sum()

13

In [76]:
df_survey[df_survey.duplicated(subset=['Timestamp'], keep=False)]

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
116,2014-08-27 12:31:41,21,Male,United Kingdom,NaN,Yes,No,No,Often,1-5,Yes,No,No,Yes,No,No,Yes,Very difficult,Yes,No,Some of them,Yes,No,Maybe,No,No,NaN
117,2014-08-27 12:31:41,27,Male,Canada,NaN,No,No,No,Rarely,6-25,No,No,Yes,Yes,Yes,Yes,Yes,Very easy,Maybe,No,Some of them,Yes,No,No,Don't know,No,NaN
138,2014-08-27 12:37:50,29,Female,United States,MD,No,No,No,NaN,6-25,No,Yes,Don't know,No,No,Don't know,Don't know,Somewhat easy,Maybe,No,Some of them,No,No,No,Don't know,No,NaN
139,2014-08-27 12:37:50,22,m,Austria,NaN,No,No,No,NaN,6-25,Yes,Yes,Don't know,No,Don't know,No,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
157,2014-08-27 12:43:28,26,male,United States,OK,No,No,No,Often,26-100,No,No,Don't know,Not sure,No,No,Don't know,Don't know,Yes,Maybe,Some of them,Yes,No,Maybe,No,No,NaN
158,2014-08-27 12:43:28,27,male,United States,UT,No,No,Yes,Rarely,26-100,Yes,Yes,No,Yes,No,No,Don't know,Somewhat difficult,Maybe,No,Some of them,Yes,No,No,Don't know,Yes,Had a co-worker disappear from work for a few ...
161,2014-08-27 12:44:51,25,F,United States,NY,No,Yes,Yes,Sometimes,500-1000,No,Yes,Yes,No,No,No,Don't know,Don't know,Yes,Yes,Some of them,Some of them,No,No,Don't know,No,NaN
162,2014-08-27 12:44:51,31,M,United States,CA,No,No,No,Never,More than 1000,No,Yes,Yes,No,No,Yes,Don't know,Don't know,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
192,2014-08-27 12:54:11,28,Male,Russia,NaN,No,No,No,Sometimes,26-100,No,Yes,No,No,No,No,Don't know,Don't know,Yes,Maybe,No,No,No,Maybe,Don't know,No,NaN
193,2014-08-27 12:54:11,35,Male,United States,CA,No,No,Yes,Rarely,6-25,No,Yes,No,No,No,No,Yes,Don't know,No,No,Some of them,Yes,No,No,Don't know,No,NaN
307,2014-08-27 14:22:43,26,M,United States,IN,No,No,No,NaN,26-100,No,Yes,No,No,No,No,Don't know,Don't know,No,No,Some of them,Some of them,No,No,Don't know,Yes,NaN
308,2014-08-27 14:22:43,25,Male,United States,OR,No,No,No,NaN,26-100,Yes,Yes,Don't know,Not sure,No,Don't know,Don't know,Don't know,No,No,Some of them,Yes,No,No,Don't know,No,NaN
384,2014-08-27 15:23:51,26,M,United States,NV,No,No,Yes,Sometimes,6-25,No,Yes,Don't know,No,No,No,Don't know,Don't know,Yes,Yes,Some of them,No,No,No,No,No,NaN
385,2014-08-27 15:23:51,27,female,United States,CO,No,Yes,Yes,Rarely,More than 1000,Yes,Yes,Yes,Yes,No,Don't know,Don't know,Don't know,Maybe,Maybe,No,Yes,No,No,Don't know,No,NaN
390,2014-08-27 15:24:47,99999999999,All,Zimbabwe,NaN,Yes,Yes,Yes,Often,1-5,No,Yes,No,Yes,No,No,No,Very difficult,Yes,Yes,No,No,Yes,No,No,Yes,NaN
391,2014-08-27 15:24:47,40,female,United States,PA,No,Yes,Yes,Rarely,More than 1000,No,No,Yes,No,Don't know,Don't know,Don't know,Somewhat easy,Maybe,Maybe,No,No,No,No,Don't know,No,NaN
453,2014-08-27 15:55:07,34,M,United States,CA,No,No,Yes,Sometimes,6-25,No,Yes,Don't know,Not sure,No,No,Don't know,Don't know,Yes,Yes,Some of them,No,No,No,Don't know,No,Now at starutp. Previously worked at big tech...
454,2014-08-27 15:55:07,27,Male,United States,OR,No,Yes,Yes,Sometimes,100-500,No,Yes,Don't know,Not sure,No,Don't know,Don't know,Don't know,Yes,No,No,No,No,Yes,Don't know,No,NaN
527,2014-08-27 17:33:52,51,Male,New Zealand,NaN,No,No,Yes,Sometimes,26-100,Yes,Yes,No,Yes,Yes,No,No,Somewhat difficult,Yes,Yes,No,No,No,No,Don't know,Yes,NaN
528,2014-08-27 17:33:52,29,M,United States,NC,No,No,Yes,Sometimes,6-25,No,Yes,Yes,Yes,No,Yes,Yes,Very easy,No,No,No,Some of them,No,No,Yes,No,NaN
703,2014-08-28 09:59:39,23,Male,United States,OH,No,No,Yes,Often,26-100,No,No,Yes,Yes,Yes,No,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
704,2014-08-28 09:59:39,43,M,United States,TN,No,Yes,Yes,Sometimes,26-100,No,No,Yes,Not sure,No,Yes,Don't know,Somewhat easy,Yes,No,No,No,No,No,No,No,NaN
840,2014-08-28 16:52:34,43,male,United States,GA,No,No,Yes,Sometimes,More than 1000,No,No,Don't know,No,No,Don't know,Don't know,Very difficult,Maybe,No,Some of them,Yes,No,No,Don't know,No,NaN
841,2014-08-28 16:52:34,36,male,United Kingdom,NaN,Yes,No,No,Sometimes,6-25,Yes,Yes,No,No,No,No,Don't know,Somewhat difficult,No,No,Yes,Yes,No,Maybe,Don't know,Yes,NaN
851,2014-08-28 16:58:33,23,M,United States,KY,No,Yes,No,NaN,26-100,Yes,Yes,Yes,Yes,No,Don't know,Yes,Don't know,Maybe,No,No,Some of them,No,No,Don't know,No,NaN
852,2014-08-28 16:58:33,21,Male,United Kingdom,NaN,No,Yes,No,Never,6-25,No,No,No,No,No,No,Yes,Somewhat easy,Maybe,No,Some of them,Some of them,No,Maybe,Don't know,No,NaN

In [79]:
df_survey.columns

Index(['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

In [81]:
df_survey.columns = (
    df_survey.columns
      .str.strip()                 # quita espacios al inicio/fin
      .str.lower()
      .str.replace(r"\s+", "_", regex=True))  # cualquier espacio → "_"

In [82]:
df_survey.describe().T

,count,mean,std,min,25%,50%,75%,max
age,1259.0,7.942815e+07,2.818299e+09,-1726.0,27.0,31.0,36.0,1.000000e+11

In [83]:
df_survey.describe(include='object').T

                          count unique                              top  freq
timestamp                  1259   1246              2014-08-27 12:44:51     2
gender                     1259     49                             Male   615
country                    1259     48                    United States   751
state                       744     45                               CA   138
self_employed              1241      2                               No  1095
family_history             1259      2                               No   767
treatment                  1259      2                              Yes   637
work_interfere              995      4                        Sometimes   465
no_employees               1259      6                             6-25   290
remote_work                1259      2                               No   883
tech_company               1259      2                              Yes  1031
benefits                   1259      3                              Yes   477
care_options               1259      3                               No   501
wellness_program           1259      3                               No   842
seek_help                  1259      3                               No   646
anonymity                  1259      3                       Don't know   819
leave                      1259      5                       Don't know   563
mental_health_consequence  1259      3                               No   490
phys_health_consequence    1259      3                               No   925
coworkers                  1259      3                     Some of them   774
supervisor                 1259      3                              Yes   516
mental_health_interview    1259      3                               No  1008
phys_health_interview      1259      3                            Maybe   557
mental_vs_physical         1259      3                       Don't know   576
obs_consequence            1259      2                               No  1075
comments                    164    160  * Small family business - YMMV.     5

In [86]:
df_survey.insert(0, "id", range(1, len(df_survey) + 1))

### Columnas

In [87]:
df_survey.columns

Index(['id', 'timestamp', 'age', 'gender', 'country', 'state', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

In [88]:
df_survey['id'].nunique()

1259

In [84]:
df_survey['timestamp'].nunique()

1246

In [155]:
df_survey['timestamp'] = pd.to_datetime(df_survey['timestamp'], errors='coerce')

In [89]:
df_survey['age'].nunique()

53

In [90]:
print(sorted(df_survey['age'].unique()))

[-1726, -29, -1, 5, 8, 11, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, 57, 58, 60, 61, 62, 65, 72, 329, 99999999999]

In [91]:
df_survey['age'].value_counts()

age
 29             85
 32             82
 26             75
 27             71
 33             70
 28             68
 31             67
 34             65
 30             63
 25             61
 35             55
 23             51
 24             46
 37             43
 38             39
 36             37
 40             33
 39             33
 43             28
 22             21
 41             21
 42             20
 21             16
 45             12
 46             12
 44             11
 19              9
 18              7
 48              6
 50              6
 20              6
 51              5
 49              4
 56              4
 57              3
 54              3
 55              3
 47              2
 60              2
 99999999999     1
 5               1
-1               1
 11              1
 8               1
 61              1
 53              1
-29              1
-1726            1
 65              1
 62              1
 58              1
 329             1
 72              1
Name: count, dtype: int64

In [93]:
mediana_age = float(df_survey['age'].median())
mediana_age

31.0

In [94]:
df_survey.loc[(df_survey['age'] < 18) | (df_survey['age'] > 75), 'age'] = mediana_age

In [95]:
df_survey['age'].value_counts()

age
29    85
32    82
26    75
31    75
27    71
33    70
28    68
34    65
30    63
25    61
35    55
23    51
24    46
37    43
38    39
36    37
39    33
40    33
43    28
41    21
22    21
42    20
21    16
45    12
46    12
44    11
19     9
18     7
48     6
50     6
20     6
51     5
49     4
56     4
55     3
57     3
54     3
47     2
60     2
58     1
62     1
65     1
53     1
61     1
72     1
Name: count, dtype: int64

In [97]:
df_survey['gender'] = df_survey['gender'].str.lower().str.strip()

In [101]:
df_survey['gender'].unique()

array(['female', 'm', 'male', 'male-ish', 'maile', 'trans-female',
       'cis female', 'f', 'something kinda male?', 'cis male', 'woman',
       'mal', 'male (cis)', 'queer/she/they', 'non-binary', 'femake',
       'make', 'nah', 'all', 'enby', 'fluid', 'genderqueer', 'androgyne',
       'agender', 'cis-female/femme', 'guy (-ish) ^_^',
       'male leaning androgynous', 'man', 'trans woman', 'msle', 'neuter',
       'female (trans)', 'queer', 'female (cis)', 'mail',
       'a little about you', 'malr', 'p', 'femail', 'cis man',
       'ostensibly male, unsure what that really means'], dtype=object)

In [102]:
mapa_generos = {
    # --- MALE ---
    'male': 'Male', 'm': 'Male', 'male-ish': 'Male', 'maile': 'Male', 'make': 'Male', 
    'msle': 'Male', 'mail': 'Male', 'cis male': 'Male', 'cis-male': 'Male', 
    'male (cis)': 'Male', 'guy (-ish) ^_^': 'Male', 'man': 'Male',
    'ostensibly male, unsure what that really means': 'Male',
    'something kinda male?': 'Male', 'mal': 'Male', 'malr': 'Male', 'cis man': 'Male',
    
    # --- FEMALE ---
    'female': 'Female', 'f': 'Female', 'woman': 'Female', 'femake': 'Female', 
    'femail': 'Female', 'cis female': 'Female', 'cis-female/femme': 'Female', 
    'female (cis)': 'Female', 'female (trans)': 'Female', 'trans-female': 'Female',
    'trans woman': 'Female',
    
    # --- NON-BINARY ---
    'non-binary': 'Non-binary', 'genderqueer': 'Non-binary', 'queer': 'Non-binary', 
    'queer/she/they': 'Non-binary', 'androgyne': 'Non-binary', 
    'fluid': 'Non-binary', 'neuter': 'Non-binary', 'enby': 'Non-binary', 
    'male leaning androgynous': 'Non-binary', 'all': 'Non-binary',
    
    # --- OTHER / PREFER NOT TO SAY ---
    'prefer not to say': 'Other/Prefer not to say',
    'other': 'Other/Prefer not to say',
    'p': 'Other/Prefer not to say',
    'a little about you': 'Other/Prefer not to say',
    'nah': 'Other/Prefer not to say',
    'agender': 'Other/Prefer not to say'
}

In [103]:
df_survey['gender'] = df_survey['gender'].map(mapa_generos)

In [104]:
df_survey['gender'].value_counts()

gender
Male                       994
Female                     251
Non-binary                  10
Other/Prefer not to say      4
Name: count, dtype: int64

In [107]:
df_survey['country'].unique()

array(['United States', 'Canada', 'United Kingdom', 'Bulgaria', 'France',
       'Portugal', 'Netherlands', 'Switzerland', 'Poland', 'Australia',
       'Germany', 'Russia', 'Mexico', 'Brazil', 'Slovenia', 'Costa Rica',
       'Austria', 'Ireland', 'India', 'South Africa', 'Italy', 'Sweden',
       'Colombia', 'Latvia', 'Romania', 'Belgium', 'New Zealand',
       'Zimbabwe', 'Spain', 'Finland', 'Uruguay', 'Israel',
       'Bosnia and Herzegovina', 'Hungary', 'Singapore', 'Japan',
       'Nigeria', 'Croatia', 'Norway', 'Thailand', 'Denmark',
       'Bahamas, The', 'Greece', 'Moldova', 'Georgia', 'China',
       'Czech Republic', 'Philippines'], dtype=object)

In [152]:
mapa_regiones = {
    # North America
    'United States': 'North America', 'Canada': 'North America', 'Mexico': 'North America', 'Bahamas, The': 'North America',
    
    # Europe
    'United Kingdom': 'Europe', 'Bulgaria': 'Europe', 'Portugal': 'Europe', 'Switzerland': 'Europe', 
    'Poland': 'Europe', 'Slovenia': 'Europe', 'Austria': 'Europe', 'Ireland': 'Europe', 'Italy': 'Europe', 
    'Croatia': 'Europe', 'Denmark': 'Europe', 'Moldova': 'Europe', 'Belgium': 'Europe', 'Netherlands': 'Europe', 
    'Germany': 'Europe', 'France': 'Europe', 'Russia': 'Europe', 'Latvia': 'Europe', 'Romania': 'Europe', 
    'Greece': 'Europe', 'Sweden': 'Europe', 'Spain': 'Europe', 'Hungary': 'Europe', 'Czech Republic': 'Europe',
    'Finland': 'Europe', 'Bosnia and Herzegovina': 'Europe', 'Norway': 'Europe', 'Georgia': 'Europe',
    
    # Asia
    'India': 'Asia', 'Thailand': 'Asia', 'Philippines': 'Asia', 'Israel': 'Asia', 'Japan': 'Asia', 'China': 'Asia',
    'Singapore': 'Asia',
    
    # South America
    'Brazil': 'South America', 'Colombia': 'South America', 'Costa Rica': 'South America', 'Uruguay': 'South America',
    
    # Oceania
    'Australia': 'Oceania', 'New Zealand': 'Oceania',
    
    # Africa
    'South Africa': 'Africa', 'Zimbabwe': 'Africa', 'Nigeria': 'Africa'
}
df_survey['region'] = df_survey['country'].map(mapa_regiones)

In [109]:
df_survey['state'].unique()

array(['IL', 'IN', nan, 'TX', 'TN', 'MI', 'OH', 'CA', 'CT', 'MD', 'NY',
       'NC', 'MA', 'IA', 'PA', 'WA', 'WI', 'UT', 'NM', 'OR', 'FL', 'MN',
       'MO', 'AZ', 'CO', 'GA', 'DC', 'NE', 'WV', 'OK', 'KS', 'VA', 'NH',
       'KY', 'AL', 'NV', 'NJ', 'SC', 'VT', 'SD', 'ID', 'MS', 'RI', 'WY',
       'LA', 'ME'], dtype=object)

In [140]:
df_survey['state'] = df_survey['state'].fillna('Not USA')

In [113]:
df_survey['self_employed'].unique()

array([nan, 'Yes', 'No'], dtype=object)

In [114]:
df_survey['self_employed'].value_counts()

self_employed
No     1095
Yes     146
Name: count, dtype: int64

In [148]:
moda_self_employed = df_survey['self_employed'].mode()
df_survey['self_employed'] = df_survey['self_employed'].fillna(moda_self_employed[0])

In [117]:
df_survey['family_history'].unique()

array(['No', 'Yes'], dtype=object)

In [118]:
df_survey['treatment'].unique()

array(['Yes', 'No'], dtype=object)

In [119]:
df_survey['work_interfere'].unique()

array(['Often', 'Rarely', 'Never', 'Sometimes', nan], dtype=object)

In [120]:
df_survey['work_interfere'] = df_survey['work_interfere'].fillna('Unknown')

In [121]:
df_survey['no_employees'].unique()

array(['6-25', 'More than 1000', '26-100', '100-500', '1-5', '500-1000'],
      dtype=object)

In [122]:
df_survey['remote_work'].unique()

array(['No', 'Yes'], dtype=object)

In [123]:
df_survey['tech_company'].unique()

array(['Yes', 'No'], dtype=object)

In [124]:
df_survey['benefits'].unique()

array(['Yes', "Don't know", 'No'], dtype=object)

In [125]:
df_survey['care_options'].unique()

array(['Not sure', 'No', 'Yes'], dtype=object)

In [126]:
df_survey['wellness_program'].unique()

array(['No', "Don't know", 'Yes'], dtype=object)

In [127]:
df_survey['seek_help'].unique()

array(['Yes', "Don't know", 'No'], dtype=object)

In [128]:
df_survey['anonymity'].unique()

array(['Yes', "Don't know", 'No'], dtype=object)

In [130]:
df_survey['leave'].unique()

array(['Somewhat easy', "Don't know", 'Somewhat difficult',
       'Very difficult', 'Very easy'], dtype=object)

In [131]:
df_survey['mental_health_consequence'].unique()

array(['No', 'Maybe', 'Yes'], dtype=object)

In [132]:
df_survey['phys_health_consequence'].unique()

array(['No', 'Yes', 'Maybe'], dtype=object)

In [133]:
df_survey['coworkers'].unique()

array(['Some of them', 'No', 'Yes'], dtype=object)

In [134]:
df_survey['supervisor'].unique()

array(['Yes', 'No', 'Some of them'], dtype=object)

In [135]:
df_survey['mental_health_interview'].unique()

array(['No', 'Yes', 'Maybe'], dtype=object)

In [136]:
df_survey['phys_health_interview'].unique()

array(['Maybe', 'No', 'Yes'], dtype=object)

In [137]:
df_survey['mental_vs_physical'].unique()

array(['Yes', "Don't know", 'No'], dtype=object)

In [138]:
df_survey['obs_consequence'].unique()

array(['No', 'Yes'], dtype=object)

In [139]:
df_survey['comments'].nunique()

160

In [141]:
df_survey['comments'] = df_survey['comments'].fillna('No comments')

In [156]:
df_survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         1259 non-null   int64
 1   timestamp                  1259 non-null   datetime64[ns]
 2   age                        1259 non-null   int64
 3   gender                     1259 non-null   object
 4   country                    1259 non-null   object
 5   state                      1259 non-null   object
 6   self_employed              1259 non-null   object
 7   family_history             1259 non-null   object
 8   treatment                  1259 non-null   object
 9   work_interfere             1259 non-null   object
 10  no_employees               1259 non-null   object
 11  remote_work                1259 non-null   object
 12  tech_company               1259 non-null   object
 13  benefits                   1259 non-null   object
 14  care_options               1259 non-null   object
 15  wellness_program           1259 non-null   object
 16  seek_help                  1259 non-null   object
 17  anonymity                  1259 non-null   object
 18  leave                      1259 non-null   object
 19  mental_health_consequence  1259 non-null   object
 20  phys_health_consequence    1259 non-null   object
 21  coworkers                  1259 non-null   object
 22  supervisor                 1259 non-null   object
 23  mental_health_interview    1259 non-null   object
 24  phys_health_interview      1259 non-null   object
 25  mental_vs_physical         1259 non-null   object
 26  obs_consequence            1259 non-null   object
 27  comments                   1259 non-null   object
 28  region                     1259 non-null   object
dtypes: datetime64[ns](1), int64(2), object(26)
memory usage: 285.4+ KB

In [157]:
df_survey.sample(5)

,id,timestamp,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments,region
275,276,2014-08-27 14:01:25,33,Male,Canada,Not USA,No,No,No,Unknown,100-500,No,Yes,Yes,No,Yes,Yes,Yes,Don't know,No,No,Some of them,Yes,No,No,Don't know,No,No comments,North America
833,834,2014-08-28 15:54:35,29,Female,United States,CA,No,Yes,Yes,Rarely,100-500,No,Yes,Yes,Not sure,Don't know,No,Don't know,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No,No comments,North America
13,14,2014-08-27 11:33:26,36,Male,United States,CT,No,Yes,No,Never,500-1000,No,Yes,Don't know,Not sure,No,Don't know,Don't know,Don't know,No,No,Yes,Yes,No,No,Don't know,No,I'm not on my company's health insurance which...,North America
250,251,2014-08-27 13:39:00,23,Male,United States,AL,No,Yes,Yes,Sometimes,26-100,Yes,No,Don't know,No,No,Don't know,Yes,Somewhat easy,Maybe,No,Some of them,Some of them,No,Yes,Yes,No,No comments,North America
1026,1027,2014-08-29 10:27:15,25,Female,United States,OR,No,No,No,Never,More than 1000,No,Yes,Yes,Yes,Yes,Yes,Don't know,Don't know,Maybe,No,Some of them,Yes,Maybe,No,Yes,No,No comments,North America

## Load: Carga de los nuevos datasets

In [158]:
df_survey.to_csv("./datasets/clean_survey.csv", index=False)
df_remote_work.to_csv("./datasets/clean_remote_work.csv", index=False)